GET http://localhost:3000/users

### Commmon User

POST http://localhost:3000/users
Content-Type: application/json

{
    "name": "Joss",
    "email": "1@email.com",
    "password": "12331!"
}


### Partner User

POST http://localhost:3000/partners/users
Content-Type: application/json

{
    "name": "Stud, o duds",
    "email": "stud@paartner",
    "password": "L1"
}

### Login

POST http://localhost:3000/auth/login
Content-Type: application/json

{
    "email": "stud@paartner",
    "password": "L1"
}

### Criação do partner

POST http://localhost:3000/partners
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MTMsIm5hbWUiOiJTdHVkLCBvIGR1ZHMiLCJlbWFpbCI6InN0dWRAcGFhcnRuZXIiLCJyb2xlcyI6WyJQQVJUTkVSIl0sImNyZWF0ZWRBdCI6IjIwMjQtMDYtMTlUMjE6MjE6NTUuMTY1WiIsInVwZGF0ZWRBdCI6IjIwMjQtMDYtMTlUMjE6MjE6NTUuMTY1WiIsImlhdCI6MTcxODgzMjExOSwiZXhwIjoxNzE4ODQyMTE5fQ.e8C0LEPID8KIXlnsFeBPi13dhVXEyI7fYvvhkQXlBNw

{
    "name": "partner 55115" 
}

###

GET http://localhost:3000/partners
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MTMsIm5hbWUiOiJTdHVkLCBvIGR1ZHMiLCJlbWFpbCI6InN0dWRAcGFhcnRuZXIiLCJyb2xlcyI6WyJQQVJUTkVSIl0sImNyZWF0ZWRBdCI6IjIwMjQtMDYtMTlUMjE6MjE6NTUuMTY1WiIsInVwZGF0ZWRBdCI6IjIwMjQtMDYtMTlUMjE6MjE6NTUuMTY1WiIsImlhdCI6MTcxODgzMjExOSwiZXhwIjoxNzE4ODQyMTE5fQ.e8C0LEPID8KIXlnsFeBPi13dhVXEyI7fYvvhkQXlBNw